noodlefrenzy/node-amqp10

.travis.yml
Makefile
package.json

- remove grunt dependency completely
- add Makefile to replace it
- Grunt functionality will be incrementally readded via Makefile

chore(test): remove Grunt dependency

---

.travis.yml

- remove node 0.11
- add node 0.12 and iojs 1.0
- opt-in to container builds (sudo: false)

chore(test): update .travis.yml

---

README.md

chore(coverage): add the right badge link

---

README.md

chore(coverage): ACTUALLY use the correct coverage badge

---

lib/types.js

- remove unused type attributes
- remove unused size and count reads in collection decoders

chore(types): remove cruft

---

lib/types/message.js

fix(message-properties): added missing amqp symbols for two fields

---

package.json
test/mock_amqp.js
test/test_amqpclient.js
test/test_codec.js
test/test_connection.js
test/test_frame_encodings.js
test/test_frame_reader.js
test/test_sasl.js
test/test_session.js
test/test_types.js
test/test_utilities.js
test/testing_utils.js

* remove unused dependencies (xml2js)
* remove duplicate dependencies
* convert all references to should to use chai
* update out-of-date dependencies (node-int64, uuid)

refactor(deps): clean dependencies and convert should to chai

---

lib/amqp_client.js
test/test_amqpclient.js

details are in the individual commits

Receive refactor

---

lib/amqp_client.js
lib/codec.js
lib/connection.js
lib/frames/attach_frame.js
lib/frames/begin_frame.js
lib/frames/close_frame.js
lib/frames/detach_frame.js
lib/frames/disposition_frame.js
lib/frames/end_frame.js
lib/frames/flow_frame.js
lib/frames/frame.js
lib/frames/frame_reader.js
lib/frames/open_frame.js
lib/frames/sasl_frame.js
lib/frames/transfer_frame.js
lib/policies/policy_utilities.js
lib/sasl.js
lib/session.js
lib/types.js
lib/types/described_type.js
lib/types/known_type_converter.js
lib/utilities.js

refactor(debug): use conventional debug namespacing

---

lib/amqp_client.js
lib/link.js
lib/policies/policy_utilities.js
lib/session.js

@noodlefrenzy hit me up on IRC before merging, have a few things to discuss here

clean link api

---

lib/amqp_client.js
lib/errors.js
lib/policies/policy_base.js
lib/utilities.js
test/unit/test_utilities.js

* added fibonacci and exponential backoff strategies
* added reconnect policy to PolicyBase
* cleaned up/standardized debug messages for connect-related events

failover refactor

---

.travis.yml
lib/frames/disposition_frame.js
lib/index.js
lib/link.js
lib/types/delivery_state.js
lib/utilities.js
package.json
test/integration/qpid/disposition.test.js

add a test case for manual disposition, exposing some weaknesses in the API

manual disposition test

---

lib/frames/flow_frame.js
lib/frames/transfer_frame.js
lib/link.js
lib/receiver_link.js
lib/sender_link.js
lib/session.js

commits should be fairly self-documenting, this was all based on agreements we made during conversation in gitter

initial refactoring of Link into SenderLink and ReceiverLink

---

.travis.yml
Makefile
lib/types/message.js
test/integration/servicebus/config.js
test/integration/servicebus/queue.test.js

Encoded creds in .travis.yml, initial send/receive test for ServiceBus queues.

Servicebus integration test - just getting started.

---

lib/amqp_client.js
lib/connection.js
lib/session.js
test/integration/servicebus/queue.test.js

Remove handlers from dead connections

---

lib/frames/attach_frame.js
lib/frames/begin_frame.js
lib/frames/detach_frame.js
lib/frames/disposition_frame.js
lib/frames/flow_frame.js
lib/frames/open_frame.js
lib/frames/transfer_frame.js
lib/types/message.js
lib/types/source_target.js
lib/utilities.js
test/integration/qpid/client.test.js

- also cleaned up described type extraction using methods for
extraction and assignment from payload

refactor(encodeOrdering): make encodeOrdering part of prototype

---

examples/simple_eventhub_test.js

If you put the createReceiver's .then clause inside the for loop, all the variables used in receiver.on end up with the value of the last partition in the bind clause.
Also, I couldn't get the filterOption to work, so I left it for a later refactor.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/162)

moved closure outside of for loop for variable independence.

---

.travis.yml
Makefile
Makefile.win
examples/simple_eventhub_test.js
test/integration/servicebus/eventhubs/client.test.js
test/integration/servicebus/eventhubs/config.js
test/integration/servicebus/queues/client.test.js

Finally actually enabling the eventhub/servicebus tests in Travis. Also, added another one for EH that tests out the time-based filter for receivers.
I'll be adding another one to make sure it actually ensures messages prior to that time don't come through, but that'll take a bit more work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/167)

Servicebus integration to travis

---

examples/eventhub_management_request.js
lib/types/message.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/168)

Add example for getting partition information from event hub.

---

Makefile
Makefile.win
api/README.md
package.json
test/integration/servicebus/eventhubs/client.test.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/169)

Adding jsdoc2md, updated api docs.

---

Makefile
Makefile.win
api/README.md
examples/eventhub_management_request.js
examples/simple_activemq_test.js
examples/simple_eventhub_test.js
examples/simple_servicebus_queues.js
examples/simple_servicebus_topics.js
lib/amqp_client.js
lib/index.js
test/integration/servicebus/eventhubs/client.test.js

Move translator to top-level include.
Cleanup examples to work with env settings from integration tests.
Fix a few comments.
Make examples jshint-conformant.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/170)

Pre ship cleanup

---

README.md
lib/index.js
lib/link.js
lib/policies/policy_utilities.js
lib/receiver_link.js
test/integration/servicebus/queues/client.test.js

Receive flow control on ack

---

lib/link.js
lib/session.js
test/unit/client.test.js

* add a new REATTACHING state for Links
* ensure that reattach attempts are cleared on disconnect
Attempts to fix #221

fix(link-reattach): ensure sessions don't reattach after disconnect

---

lib/link.js
test/testing_utils.js
test/unit/link.test.js

fix(detach): don't always reject promise if !close

---

lib/policies/service_bus_policy.js

Attempted fix for https://github.com/Azure/azure-event-hubs/issues/118

Avoid jsonifying Buffers for ServiceBus and variants.

---

lib/adapters/translate_encoder.js
lib/index.js
lib/types.js
package.json
test/integration/servicebus/eventhubs/client.test.js
test/integration/servicebus/eventhubs/streams.test.js
test/testing_utils.js
test/unit/frames.test.js
test/unit/translator_encoder.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/302)

refactor(translator_encoder): replace with new exported `Type` object

---

.travis.yml
package.json
test/testing_utils.js
test/unit/address.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/347)

Merges #329 and #330 in an attempt to fix build issues

---

README.md

changes in readme to point to correct default policy file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/339)

correct link to default policy

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/351)

Update version and changelog for v3.6.0
