noodlefrenzy/node-amqp10

lib/codec.js
lib/connection.js
lib/frames/frame_reader.js
lib/types.js
package.json
test/mock_amqp.js
test/test_codec.js
test/test_connection.js
test/test_frame_encodings.js
test/test_frame_reader.js
test/test_sasl.js
test/test_types.js
test/test_utilities.js
test/testing_utils.js

Closes https://github.com/noodlefrenzy/node-amqp-1-0/issues/35, possibly https://github.com/noodlefrenzy/node-amqp-1-0/issues/47 as well
This was a pretty straight-forward port, and seems to have resolved the parsing issues I was seeing previously. I've intentionally left the sort of awkward combination of "slice(0, offset); consume(offset)" in the code as a sort of reminder that we should eventually be using streams/token-parser, but this is a good stopgap for the moment.

refactor(buffers): use buffer lists instead of a circular buffer

---

lib/frames/attach_frame.js
lib/frames/begin_frame.js
lib/frames/detach_frame.js
lib/frames/disposition_frame.js
lib/frames/flow_frame.js
lib/frames/open_frame.js
lib/frames/transfer_frame.js
lib/sasl.js
package.json

Lodash is a highly tested, and often used, library containing a number of
very useful methods some of which have been duplicated in this library's
utility class. This change introduced lodash as a dependency, and opts
for using its methods over the custom implementations. For starters, each
frame has been converted to using lodash.defaults.

refactor(defaults): use lodash defaults instead of custom utilities

---

lib/amqp_client.js
lib/session.js
lib/types/delivery_state.js

There was a certain amount of duplication in the disposition frame
handling which was easily consolidated. Also, testing against a QPID
server exposed some issues with rejected messages. I've left a comment
in there for future discussion about what should be returned in the
event that a rejection error is not provided. Note that a few debug
messages were temporarily added to help trace errors in the meantime
before a general debug cleanup occurs.

refactor(disposition): reduced duplication, added error handling

---

lib/frames/frame_reader.js

FrameReader used to be a large collection of switch statements. This
change reduces that complexity by splitting into the concept of AMQP
and SASL frame internal reader classes. A number of other readability
cleanups occurred including: unrolling a number of if statements to
fail early, as well as registration of Readers.
**NOTE:** I'd like to further discuss this PR, because while the readability of having multiple internal FrameReaders is nice, this can be optimized even more to create a single registry in the FrameReader class encompassing all frame types we accept. It would reduce readability imho, but probably improve performance. Furthermore, if we can agree on what all *_frame.js files should look like, we can automate the building of the frame registry.

refactor(frame_reader): reduce complixity and enhance readability

---

lib/frames/frame_reader.js
test/test_frame_reader.js

Refactored and filled out the frame_reader test cases to support
most parsing cases (with a few exception ommissions), as well as
reformatting the test output. This should bring the coverage of
frames to about 90%.

test(frame_reader): improve test coverage of supported types

---

lib/connection.js
test/test_amqpclient.js
test/test_codec.js
test/test_connection.js
test/test_sasl.js
test/test_session.js
test/testing_utils.js

There were a number of cases where setTimeout was being used
inappropriately throughout our test suites. This includes a
refactoring for asserting state transitions, as well as outright
removal of setTimeout for the AMQPClient tests.

perf(tests): dramatically speed up test runs

---

README.md
api/README.md
lib/amqp_client.js
package.json

As discussed this change introduces a project name change. The
proposed benefits are as follows:
- name reflects node best practices
- easier to find the project on npmjs and google
It is early enough in the projects life that this should not cause
too much disruption, so now seems a better time than later to make
the change.
**NOTE:** This will require a little more work in terms of actually renaming the project on github, travis and code climate. I also suggest a bump in version (perhaps a minor version bump, or even *gasp* the dreaded major version bump :smile:)

chore(project-name): rename project to node-amqp10

---

lib/connection.js
lib/frames/begin_frame.js
lib/frames/frame.js
package.json
test/mock_amqp.js
test/test_connection.js
test/test_frame_encodings.js
test/test_sasl.js
test/test_session.js
test/testing_utils.js

A few things going on here:
- remove all the temporary <frameType>buf() methods from tests,
leading to a more declarative form for what the expected
requests and responses are for a test sequence
- removal of the Frame.outgoing helper function
This is the first step towards removing the buffer-builder from
the codebase. Since we are working with streams, there should be
no need to actually use a buffer builder. Now that this is in
place, we are able to use modules like buffer-more-ints to work
directly with streams (initially) for outgoing encoding.

refactor(test-send-buffers): streamline outgoing buffers for tests

---

test/test_types.js

This format for the types test makes it a lot easier to read whats
actually being tested, as well as being easier to compare to the
actual spec. Decoding tests were filled out per the spec and what
decoders are currently implemented. More complete Encoding tests
are to follow

refactor(types-test): reformat and add tests for decoder

---

README.md
lib/codec.js
lib/frames/frame.js
lib/types.js
package.json
test/test_types.js
tools/formatRx.js

butils is not needed, so this removes it for the sake of "buffer
purity". Also, I've cleaned up the types array removing needless
string allocations.

refactor(remove-butils): remove butils and cleanup type array

---

lib/codec.js
lib/types.js
test/test_codec.js
test/test_frame_encodings.js
test/test_types.js

First shot at complete coverage for all currently supported scalar
and collection types. Switched to using ForcedType's for all the
encoding to make sure we're covering what we think we're covering.
There were a few changes made to tests, mostly where null values
were being encoded incorrectly as full values rather than their
<type>-null variant.

test(encoding-decoding): improve test coverage for encoding/decoding

---

lib/types.js
test/test_types.js

This change removes some needlessly duplicated code paths in the
types system by using builders defined on a per-encoding basis
directly. A futher optimization was added to use the first encoding
if a top-level builder was not defined.

refactor(type-builders): always use encoding specific builders

---

lib/codec.js
lib/types.js
test/test_types.js

This brings our coverage for supported AMQP types to 100%. Because
forced types were not properly implemented in codec.encode, we will
probably lose a certain amount of overall coverage (since it will
not test all the non-forced branches anymore), but that can easily
be reimplemented.

test(types): full coverage for supported AMQP types

---

lib/types/message.js

Message.Properties omitted the "correlation-id" field, and did not
properly handle undefined values for the following fields:
- absolute-expiry-time
- creation-time
- group-sequence

fix(message-properties): add missing field and correct null values

---

lib/amqp_client.js
lib/index.js
lib/types/message.js
package.json

* ```require('amqp10');``` now returns an object that currently contains only ```Client```, opening up for a future where we might want to export other internal parts of the library. This is a breaking change as all users will need to modify their code to read: ```var AMQPClient = require('amqp10').Client;```
* Message properties have been exposed in both send and receive methods, allowing finer control over the metadata associated with messages
* A small fix was added for the previously modified Properties class. Since the ctor is being used for coding and encoding, sometimes the content-type and content-encoding fields might not actually be AMQPSymbols, and therefore accessing 'contents' of those values will throw an error.

new breaking changes

---

lib/amqp_client.js
test/test_amqpclient.js

There were a number of locations where connect was called in the
event that a user had not previously connected. As this is prone
to error, it's being removed in favor forcing users to call connect
explicitly.

refactor(connect): remove side-effecty connect calls

---

lib/types/message.js

the previous "fix" for this was incorrectly incrementing the array position when checking for an incoming AMQPSymbol

fix(message-properties): properly convert symbols from described

---

lib/amqp_client.js
test/test_amqpclient.js

Previously we were not resolving attempts to create a receiver with
existing links that were either in the process of attaching or
attached.

fix(cached-receivers): resolve receiver links that already exist

---

lib/link.js
lib/session.js

Circular dependencies between Link and Session were causing the
objects to be imported incompletely. As a stopgap for a proper
solution where Session listens for Link events properly, two
private methods are used to route the attachment signalling.

fix(link-attach): fix attachment messaging issues due to deps

---

lib/amqp_client.js
test/integration/qpid/client.test.js

Bug missed in the promisification of createReceiver where callbacks
passed in with createReceiver during attachment were not retained.

fix(multiple-receivers): register callback when attaching

---

lib/amqp_client.js
lib/connection.js
lib/link.js
lib/session.js

* cleanup and standardize event names
* fix two EventEmitter leaks in link.js related to promisification

Event cleanup + EventEmitter leak fixes

---

.travis.yml
lib/frames/disposition_frame.js
lib/link.js
lib/types/delivery_state.js
lib/utilities.js
package.json
test/integration/qpid/disposition.test.js

* provide two new methods Link.accept and Link.reject to handle manual disposition
* use Link.accept to enable our auto-settle behavior, by sending disposition frames upon dequeueing messages
* add an integration test proving this all works
* fixed an issue with DispositionFrame not using the proper channel number

send disposition frames

---

lib/amqp_client.js
lib/sender_link.js
lib/session.js
test/unit/test_amqpclient.js

Moved sendMessage out of Session into SenderLink. At the same time
unified the two sendMessage's in SenderLink into just the private
version, in anticipation of moving AMQPClient.send into SenderLink

refactor(SenderLink): unify sendMessage implementations

---

lib/amqp_client.js
test/integration/qpid/disposition.test.js
test/unit/test_amqpclient.js

This allows the user to specify a custom receiver link policy when using AMQPClient.createReceiver. A number of other cleanups are included in this PR, but should be relatively easy to follow (they are incremental, commits should be self-explanatory)

feat(createReceiver): allow user to specify receiver link policy

---

lib/codec.js
lib/types.js
test/integration/qpid/types.test.js
test/unit/test_types.js

Timestamps in AMQP 1.0 are expressed as 64bit unsigned integers, of
course this doesn't jive with Javascript. As a convenience to our
users, this patch defaults to converting all timestamps (incoming
and outgoing) to Date objects. This can be imprecise, and we will
need to investigate future means of opting out of this conversion.

refactor(timestamps): use Date as the primary expression of ms64

---

test/unit/client.test.js
test/unit/mocks/index.js
test/unit/mocks/server.js
test/unit/test-fixture.js

Currently only supports response sequences, and is otherwise a
general refactoring of the existing mock_amqp.js MockServer with
the addition of promisifying the setup/teardown methods

feat(MockServer): add refactored MockServer

---

lib/session.js
test/integration/qpid/disposition.test.js

Previously we ignored the role of the incoming disposition frame,
and forwarded these frames to the _dispositionRecieved method of
all links we knew about. This patch corrects this behavior, and
includes an integration test verifying that frames are forwarded
to the appropriate link types.

fix(disposition): only send disposition to relevant links by role

---

lib/amqp_client.js
lib/receiver_link.js
test/integration/qpid/client.test.js
test/integration/servicebus/queue.test.js
test/unit/test_amqpclient.js

This greatly simplifies the internals for receiver link creation,
aligning it more closely with sender link creation (so we can begin
to share code between them). It also makes the API more explicit by
requiring the user to understand that the receiver link is indeed
an EventEmitter and should be used that way.

feat(Client): remove receipt callback on createReceiver

---

lib/amqp_client.js
test/unit/mocks/session.js
test/unit/test_amqpclient.js

The general idea here was to expose how similar createSender and createReceiver actually were. By cleaning up, and refactoring these methods, it's pretty clear that they share most of the same code. Additionally, I opted to listen directly to created links for events like `Link.Attached` in order to get around issues we had previously with needing to do string checks for incoming attached events.

Link creation cleanup

---

lib/amqp_client.js
lib/link.js
lib/sender_link.js
lib/session.js
test/unit/mocks/receiver_link.js
test/unit/mocks/sender_link.js
test/unit/mocks/session.js
test/unit/test_amqpclient.js
test/unit/test_session.js

There are some cleanups here (removing events that shouldn't be used anymore, generally going back on my stupid decision to put namespaces in event names, etc), but more importantly is the change to remove attaching/attached tracking for links inside AMQPClient. It is now the responsibility of a Session to track Link state, and the Client's create[Sender,Receiver] methods are merely proxies at this point to Session.createLink.

refactor(links): move responsibility of Links fully to Session

---

lib/amqp_client.js
lib/policies/default_policy.js
lib/policies/event_hub_policy.js
lib/policies/service_bus_policy.js
lib/policies/service_bus_queue_policy.js
lib/policies/service_bus_topic_policy.js
lib/sender_link.js
lib/utilities.js
test/integration/qpid/receiver_link.test.js
test/unit/test_utilities.js

This patch adds support for defining a subject in the name of a link during link creation. On the receiver side this adds a filter for the subject, and on the sender side this adds a default subject to the message properties (if one does not currently exist).

feat(default-subject): allow specifying subjects in link names

---

lib/receiver_link.js
test/integration/qpid/disposition.test.js

_checkCredit was previous called any time an incoming message was
received, however this doesn't necessarily jive with users trying
to maintain granular control over the flow of incoming messages.
Now, _checkCredits is only called on disposition.

refactor(checkCredit): check credits only on disposition

---

examples/servicebus_reconnect.js
lib/amqp_client.js
lib/link.js
lib/policies/default_policy.js
lib/policies/service_bus_policy.js
lib/session.js
lib/utilities.js
test/unit/test_amqpclient.js

I was closer to right than you were - it was more than just not setting session to null.
- Remove reattach logic from client
- Stop setting session to null on disconnect
- Stop session from clearing link state on detach
- Add reattach policies for link, akin to client's reconnect policies
- Ensure link doesn't attempt reattach if it's detached by our side
- Add a "forceDetach" to force existing links into a detached state if the session/connection is killed

Keep session links

---

lib/receiver_link.js

* Add two new disposition outcomes to ReceiverLink: Released and Modified
* Share common code between all disposition methods, allowing a user to optionally directly use the   `settle` method as well
* Documentation!

feat(ReceiverLink): add Released and Modified outcomes

---

lib/amqp_client.js
lib/frames/attach_frame.js
lib/frames/detach_frame.js
lib/link.js
lib/policies/default_policy.js
lib/policies/service_bus_policy.js
lib/receiver_link.js
lib/sender_link.js
lib/session.js
lib/utilities.js
test/integration/qpid/disposition.test.js
test/unit/mocks/session.js
test/unit/test_amqpclient.js
test/unit/test_session.js

see #149 
includes:
* renaming `options` to `policyOverrides`
* renaming `senderLinkPolicy.options` and `receiverLinkPolicy.options` to `attach`

refactor(link-options): standardize link options for link creation

---

lib/frames/attach_frame.js
lib/frames/begin_frame.js
lib/frames/detach_frame.js
lib/frames/disposition_frame.js
lib/frames/flow_frame.js
lib/frames/open_frame.js
lib/frames/transfer_frame.js
lib/sender_link.js
lib/types/message.js
lib/types/source_target.js
lib/utilities.js
test/integration/qpid/client.test.js
test/integration/qpid/sender_link.test.js

SenderLink.send currently only accepts a signature in the form  of
(body, messageOptions), this patch allows the user to send the
entire formed message as the first parameter.
**NOTE** depends on #155, this PR will be much smaller once that is accepted and this is rebased

feat(SenderLink): accept a full message as the first param for send

---

.travis.yml
lib/session.js
test/integration/qpid/client.test.js

Previously this was not possible because of a bug in qpidd 0.32,
however I've updated the qpid ppa to include version 0.34 and we
can now include this integration test

test(Link): add qpid integration test for link detachment

---

lib/types/message.js
test/unit/test_frame_encodings.js

- skip checks for body.size and Array.isArray when encoding the
message body
- set message body to content.body || body, no default to []

refactor(Message): reduce needless complexity of body parsing

---

lib/connection.js
test/unit/test_connection.js

my local QPID server requires SASL auth and i forgot to put my credentials in the connection string. the resulting infinite loop essentially performed a DOS attack on my server until it crashed.
here is the code:
```javascript
var AMQPClient = require('amqp10');
var client = new AMQPClient();
client.connect('amqp://localhost/myqueue')
.then(function() {
client.receive(function (rx_err, message) {
// ... check for errors ...
console.log('Rx message: ');
console.log(JSON.parse(message.body));
});
return client.send(JSON.stringify({ key: "Value" }));
})
.catch(function(err) {
console.log("error: " + err);
});
```
```
node app.js
Tue, 29 Sep 2015 21:44:09 GMT amqp10-client Connecting to amqp://localhost/myqueue
Tue, 29 Sep 2015 21:44:09 GMT amqp10-Connection Connecting to localhost:5672 via …
```

DOS attack when server requires SASL and client doesnt give creds

---

lib/amqp_client.js
lib/session.js

This is primarily important for reconnect scenarios where links
have already been created. In those cases, the links otherwise would
be left with an "attached" or "attaching" state and would therefore
never have been reconnected.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/166)

refactor(AMQPClient): reset link state on clearConnectionState

---

lib/connection.js
lib/errors.js
lib/index.js
lib/link.js
lib/session.js
test/unit/test_connection.js
test/unit/test_session.js

Note: I crack the condition AMQPSymbol, since we only want the contents.
Also, adding a VersionError since we were dumping a raw string out as an error there.

Adding AMQPSymbol to index, wrapping AMQPErrors into exposed type

---

lib/types.js
test/unit/test_types.js

The first step towards dropping our dependency on node-int64. 
@noodlefrenzy while you're at it, you might want to take a look at the code I already submitted for ulong/long encoding. It should have gone into review, but I think I was a bit over-eager there (it's right next to the code in this PR, so it shouldn't be hard to seek out).

refactor(long): directly embed encoding for ulong/long

---

lib/connection.js
lib/types.js
lib/types/amqp_error.js
lib/types/composite_type.js
lib/types/error_condition.js
lib/utilities.js
test/unit/client.test.js
test/unit/policies/qpid_java.test.js
test/unit/test_connection.js
test/unit/test_sasl.js
test/unit/test_session.js
test/unit/types/errors.test.js

Not too much craziness going on here, but definitely enough to
warrant comment:
- error conditions have all been moved to the ErrorCondition enum
module. They are enumerated both by legacy enum format
(e.g. InternalError, or LinkRedirect), but also now by names
used in the spec ('internal-error', 'link:redirect'). This
opens us up to the possibility of users simply needing to use
a string in order to send the required error.
- errors can be specified by full use of the AMQPError type
internally (it is not exported), as well as by a plain object
(e.g. { condition: 'internal-error', description: 'test' }), or
just a string (for the mandatory condition field).
- any unknown errors will throw an EncodingError
- tests for all of this are baked in

refactor(errors): support encoding of AMQPErrors

---

lib/receiver_link.js
test/integration/servicebus/queues/client.test.js
test/integration/servicebus/queues/config.js
test/testing_utils.js
test/unit/frames.test.js
test/unit/mock_amqp.js
test/unit/mocks/server.js
test/unit/test_codec.js
test/unit/test_connection.js
test/unit/test_sasl.js
test/unit/test_session.js
test/unit/test_types.js
test/unit/test_utilities.js
test/unit/types/errors.test.js
test/unit/types/message_sections.test.js

… to avoid races/collisions in parallel travis runs.
Oh, and add a little extra debug information for some dispo frame (lack of) processing.

Split ServiceBus Queue tests by process version

---

lib/connection.js

Small modification to connection.js to allow any SSL options to be passed directly to the transport, while keeping the possibility to specify certFile/caFile/keyFile and have amqp10 read the file for the user

Allow sslOptions to be passed directly to the transport.

---

lib/utilities.js

`err.errorInfo` seem to be `undefined` when `wrapProtocolError` is called, and it looks like what used to be `errorInfo` is now `info`.
FYI the iothub-explorer tool in the Azure IoT SDK relies on testing the content of this `info` property to detect amqp redirections and subsequently connect to the proper event hubs endpoint when monitoring events sent by devices, so this blocks our migration to v3.x.x

Fix a typo in utilities.wrapProtocolError

---

lib/transport/abstract_transport.js
lib/transport/index.js
lib/transport/net_transport.js
lib/transport/tls_transport.js
lib/utilities.js

Seemed to be using tabs rather than the 2 spaces that the rest of the
codebase uses.

whitespace-only fix indenting in lib/transport

---

lib/frames.js
lib/session.js

Previously we were logging a selection of received frames via the
_processFrame handler(s) in session.js, but this ignores (e.g.,) a
received OpenFrame (which is handled in connection.js). It seems more
consistent to be logging received frames within the framing debug where
we currently log all sent frames.

refactor(debug): output all received frames

---

lib/connection.js
test/unit/client.test.js

There were a couple of bugs here:
- you couldn't specify a 0 for (local) idleTimeout, so we always flowed
something in our OpenFrame
- the client was incorrectly selecting a minimum value between the local
and remote idleTimeouts and then using that as the frequency with
which empty frames should be sent to the server. It should only obey
the remoteIdleTimeout for emitting heartbeats
NB: currently, although we flow an idleTimeout in our OpenFrame, we
don't actually monitor whether or not the remote-end actually sends us
data within this interval, nor do we disconnect them if they don't.

fix(heartbeat): local vs remote idleTimeouts

---

lib/index.js
lib/types/message.js
test/unit/types/message_sections.test.js

Allow a user to create a specific DescribedType in their message.body and honour this at encoding time.
-- 
As a first pass, this exposes a way of satisfying the functionality desired in #255, although it does require use of the internal DescribedType object in the client application. 
An alternative solution would be to allow the user to specify in their policy an encoding map of JavaScript objects and their desired message formats, perhaps exposing constants for the 0x75, 0x76, 0x77 hex type values.

feat(types): allow DescribedType to be passed as the message.body

---

lib/sasl.js

This sends them through the normal connectionError chain rather than just throwing them in place which ends up on the uncaughtException handler.

fix(sasl): pass errors to callback, don't throw

---

lib/errors.js
lib/sender_link.js
test/unit/sender_link.test.js

If a rejected disposition is received for a given transfer and it
lacks an error message, we erroneously resolved the send promise
rather than rejecting and indicating a rejection. If the error is
missing, we now default construct an error and reject with that.

fix(sender-link): suppplement missing error in rejected dispo

---

lib/codec.js
test/unit/test_codec.js

Addresses the bug in #274 by only reading an extra byte for fixed-width values if the code is not provided by `forcedCode`

Only decode extra byte if not forcedCode

---

lib/amqp_client.js
test/unit/mocks/index.js
test/unit/receiver_link.test.js
test/unit/sender_link.test.js

Through an initial misunderstanding of the order of operations when
using `u.deepMerge` link policies at link creation were erroneously
overwriting user provided policyOverrides. This patch corrects this
behavior.

refactor(link-policy): reorder link policy merge during create

---

lib/connection.js

Using node 0.10, when `Connection.prototype._terminate()` is called, `this._transport.end()` calls `socket.end()` which generates an event that leads to `_terminate()` being called again synchronously (meaning the first call to `_terminate()` is still waiting for `this._transport.end()` to return while the second call nullifies the `_transport` object. 
Once the second call is finished, the first call continues and throws an exception when trying to call `this._transport.terminate()`.
This PR should prevent that from happening :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/290)

Prevent exception if transport is already null when Connection.prototype._terminate() is called twice

---

lib/sender_link.js

Some libraries that make use of this library (https://github.com/Azure/azure-event-hubs-node) were making use of the option field as "annotations" rather than "messageAnnotations." This caused failures when setting the partition key in Azure Event Hubs. Simple fix below to update some of the documentation. It looks correct in other spots. Not sure if the field changed at a certain point?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/308)

Fix documentation to reference correct annotation field name

---

lib/policies/policy.js
test/unit/address.test.js

Fix a bug which truncated passwords containing a ':' character because
the parseAddress function relied upon node's url.parse().auth which
returns the user:pass pair already URI-decoded.
Fixes #318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/319)

fix(address-parsing): don't truncate ':' passwords

---

package.json
test/testing_utils.js
test/unit/address.test.js

A [couple of tests](https://travis-ci.org/noodlefrenzy/node-amqp10/builds/234319960) fail on the master branch, as a result of downlevel changes in node core. Specifically, `node>=5.7.0` adds [encodeAuth()](https://github.com/nodejs/node/commit/db9128135f382e22202d900263e872d8b48f0050#diff-bbc5176adff1bbc01acd61bfc85d049fR924) (see [changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V5.md#2016-02-23-version-570-stable-rvagg) for which release it landed in - `5.7.0`) which inteligently __doesn't__ encode `:` as a uri component when creating a [Url](https://nodejs.org/api/url.html#url_class_url). Rather than make any changes to our library to normalize this behavior across versions (which feels like a bad fix, since this behavior is consistent with core) we added …

update tests to support different runtime versions

---

.travis.yml
lib/amqp_client.js
lib/policies/policy.js
lib/policies/service_bus_policy.js
lib/session.js
test/integration/qpid/client.test.js
test/unit/client.test.js
test/unit/mock_amqp.js
test/unit/policies/policy.test.js
test/unit/policies/qpid_java.test.js
test/unit/test_amqpclient.js
test/unit/test_session.js

Addresses https://github.com/noodlefrenzy/node-amqp10/issues/331 by adding the ability to create multiple sessions on the same client/connection and providing policy options for reestablishing the session on end. This feature set is designed to better align the capabilities of amqp10 with the session pattern supported by Azure Service Bus and bring the retry logic inline with what is used for reattach and reconnect.
**Features**
**Tests**
Please take a look and let me know what you think of the change. I'm open to changing the design/approach if people have other thoughts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/noodlefrenzy/node-amqp10/332)

feat(session): add support for multiple sessions per client

---

lib/session.js
test/unit/test_session.js

With `reestablish` enabled for sessions, the session can end up in a state where it is trying to reestablish itself while the connection is trying to do the same, leading to duplicate calls to `begin()`. The following has been changed to better handle this situation and others like it:
* Disable the `begin()` attempt (and any further retries) if the link isn't still `UNMAPPED`. We already handle if the connection is broken, but this handles the connection coming down and back up (with a corresponding `begin()` call) while we're waiting to retry.
* Guard against initializing a session multiple times. Since `begin()` isn't idempotent, calling it on a session that is already active with attached links will cause a second session to be established and the links to be implicitly assigned to …

fix(session): disable reestablish on disconnect and guard against duplicate begin() calls
